replicaCount: 1

image:
  repository: "mydockerrepo/app"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5
